services:
  # Grafana container
  grafana:
    image: grafana/grafana:main-ubuntu
    container_name: grafana
    expose:
      - 3000
    volumes:
      - grafana_data:/var/lib/grafana:rw
    networks:
      internal_network:
        ipv4_address: 172.16.238.10
  
  # Prometheus container
  prometheus:
    image: prom/prometheus:v3.6.0
    container_name: grafana
    expose:
      - 9090
    volumes:
      - prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus:rw
    networks:
      internal_network:
        ipv4_address: 172.16.238.20

volumes:
  grafana_data:
  prometheus_data:

networks:
  internal_network:
    name: internal_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"