services:
  # Grafana container
  grafana:
    image: grafana/grafana:main-ubuntu
    container_name: grafana
    expose:
      - 3000
    environment:
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_ROOT_URL=http://localhost:80/grafana
    volumes:
      - grafana_data:/var/lib/grafana:rw
    networks:
      internal_network:
        ipv4_address: 172.16.238.10
  
  # Prometheus container
  prometheus:
    image: prom/prometheus:v3.6.0
    container_name: prometheus
    expose:
      - 9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus:rw
    networks:
      internal_network:
        ipv4_address: 172.16.238.20

  # NGINX container and metrics exporter
  nginx:
    image: nginx:1.29
    container_name: nginx
    ports:
      - 80:80
      - 8080:8080 # For metrics extraction
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      internal_network:
        ipv4_address: 172.16.238.30

  nginx_metrics:
    image: nginx/nginx-prometheus-exporter:1.5.0
    container_name: nginx_metrics
    expose:
      - 9113
    networks:
      internal_network:
        ipv4_address: 172.16.238.40

volumes:
  grafana_data:
  prometheus_data:

networks:
  internal_network:
    name: internal_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"