services:
  # Grafana container
  grafana:
    image: grafana/grafana:12.3.0-18329792253-ubuntu
    container_name: grafana
    restart: always
    expose:
      - 3000
    environment:
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_ROOT_URL=http://localhost:80/grafana
    volumes:
      - grafana_data:/var/lib/grafana:rw
    networks:
      internal_network:
        ipv4_address: 172.16.238.10
  
  # Prometheus container
  prometheus:
    image: prom/prometheus:v3.6.0
    container_name: prometheus
    expose:
      - 9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus:rw
    networks:
      internal_network:
        ipv4_address: 172.16.238.20

  # NGINX container and metrics exporter
  nginx:
    image: nginx:1.29
    container_name: nginx
    restart: always
    ports:
      - 80:80
    expose:
      - 8080 # For metrics extraction
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      internal_network:
        ipv4_address: 172.16.238.30

  nginx_metrics:
    image: nginx/nginx-prometheus-exporter:1.5.0
    container_name: nginx_metrics
    expose:
      - 9113
    networks:
      internal_network:
        ipv4_address: 172.16.238.40

  # Database container (PostgreSQL)
  postgresql:
    image: postgres:18
    container_name: postgresql
    restart: always
    shm_size: 128mb # Shared memory cap (recommended by docs)
    expose:
      - 5432
    volumes:
      - postgresql_data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=default
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
    networks:
      internal_network:
        ipv4_address: 172.16.238.50

volumes:
  grafana_data:
  prometheus_data:
  postgresql_data:

networks:
  internal_network:
    name: internal_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"