apiVersion: 1

providers:
  - name: "nginx_metrics"
    orgId: 1
    folder: "NGINX"
    type: file
    disableDeletion: true
    updateIntervalSeconds: 10
    allowUiUpdates: true
    options:
      path: /var/lib/grafana/dashboards
      foldersFromFilesStructure: true
  
  - name: "postgresql_metrics"
    orgId: 1
    folder: "PostgreSQL"
    type: file
    disableDeletion: true
    updateIntervalSeconds: 10
    allowUiUpdates: true
    options:
      path: /var/lib/grafana/dashboards
      foldersFromFilesStructure: true