apiVersion: 1

providers:
  - name: "Dashboard provider"
    orgId: 1
    folder: "NGINX"
    type: file
    disableDeletion: true
    updateIntervalSeconds: 10
    allowUiUpdates: true
    options:
      path: /var/lib/grafana/dashboards
      foldersFromFilesStructure: true